### ISSUE TITLE
Optim API

### ISSUE THREAD

**Issue by pkofod** [rgiordan/LinearResponseVariationalBayes.jl#2]
Hello there! Is this package actively maintained? I just wanted to say that there has been a new API out for some time. I think you might only need to change `:newton` to `Newton()`. We also have a trust region based Newton solver coming out soon that might be interesting to try.

**Comment by rgiordan** [comment]
Thanks for asking -- this isn't really actively maintained, though I'd like to keep it public for now since it was used for results a published paper. 

I'm aware of the trust region method in ```Optim.jl``` because I wrote it.  :)  I'm happy to see it being promoted!

**Comment by pkofod** [comment]
Haha, sorry, I hadn't seen it was your package :)
